name: Py-Installer Build Windows
name: Build and Deploy Application

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your required Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      # - name: Run tests
      #   run: |
      #     python -m unittest discover -s tests -p "*.py"

      # Step 5: Build executable with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile -i src/_icon.ico -w src/main.py  # Update with your main script path
        # The output executable will be in the "dist" directory

      # Step 6: Upload the built executable as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: dist/*  # Upload the executable from the dist folder
