name: Py-Installer Build Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust this to match your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # Ensure PyInstaller is installed

      # Step 4: Build the application with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile your_script_name.py  # Replace with your main script name
        # The output executable will be in the "dist" directory

      # Step 5: Upload the built executable as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: dist/*  # Upload the executable from the dist folder
